name: fft_games
description: "A suite of games similar to NYT."
publish_to: "none"

version: 1.0.2+3

environment:
    sdk: ^3.9.0

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8

    logging: ^1.3.0
    provider: ^6.1.5+1
    go_router: ^16.2.1
    shared_preferences: ^2.5.3
    collection: ^1.19.1
    material_symbols_icons: ^4.2874.0
    path_drawing: ^1.0.1
    svg_path_parser: ^1.1.2

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true

    assets:
        - pubspec.yaml
        - assets/fosterdle/allowed.txt
        - assets/fosterdle/wod.txt
        - assets/fosteroes/testpuzzles/

    fonts:
        - family: FacultyGlyphic
          fonts:
              - asset: fonts/FacultyGlyphic-Regular.ttf
