name: fft_games
description: "A suite of games similar to NYT."
publish_to: "none"

version: 1.1.10+15

environment:
    sdk: ^3.10.0

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8

    fft_games_lib:
        path: ../fft_games_lib

    logging: ^1.3.0
    provider: ^6.1.5+1
    go_router: ^17.0.0
    shared_preferences: ^2.5.3
    collection: ^1.19.1
    path_drawing: ^1.0.1
    svg_path_parser: ^1.1.2
    defer_pointer: ^0.0.2
    confetti: ^0.8.0
    intl: ^0.20.2
    flutter_lints: ^6.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true

    assets:
        - assets/fosterdle/allowed.txt
        - assets/fosterdle/wod.txt
        - assets/tile-fosterdle.png
        - assets/tile-fosteroes.png

    fonts:
        - family: FacultyGlyphic
          fonts:
              - asset: assets/FacultyGlyphic-Regular.ttf
